section Section1;

shared IntercoCustomers = let
    // 1. Table des clients interco
    Source = #table(
        type table [Company = text, Sell_to_Customer_No = text],
        {
            {"JAVA LU", "C376"},     // client = JAVA BE
            {"JAVA BE", "C000200"}   // client = JAVA LU
        }
    ),

    // 2. Clé pour la relation avec SalesDoc_2Socs_2025
    AddKeyCompanyCust = Table.AddColumn(
        Source,
        "Key_Company_Cust",
        each [Company] & "|" & Text.From([Sell_to_Customer_No]),
        type text
    )

in
    AddKeyCompanyCust;

shared #"Value entries LU" = let
    Source = OData.Feed(
        "https://api.businesscentral.dynamics.com/v2.0/ad140881-5aae-4f5d-8941-89111ecfcdcc/Production/ODataV4/Company('JAVA%20Distribution')/ValueEntries?$filter=Posting_Date ge 2026-01-01",
        null,
        [Implementation="2.0"]
    ),
    AddCompany = Table.AddColumn(Source, "Company", each "JAVA LU", type text)
in
    AddCompany;

shared #"Value entries BE" = let
    Source = OData.Feed(
        "https://api.businesscentral.dynamics.com/v2.0/ad140881-5aae-4f5d-8941-89111ecfcdcc/Production/ODataV4/Company('JAVA%20BE')/ValueEntries?$filter=Posting_Date ge 2026-01-01",
        null,
        [Implementation="2.0"]
    ),
    AddCompany = Table.AddColumn(Source, "Company", each "JAVA BE", type text)
in
    AddCompany;

shared VE_2Socs_2026 = let
    // 1. Combine les Value Entries des deux sociétés
    Combined = Table.Combine({#"Value entries LU", #"Value entries BE"}),

    // 2. Clé pour la relation avec Sales Docs (Company + Document No)
    AddKeyCompanyDoc = Table.AddColumn(
        Combined,
        "Key_Company_Doc",
        each [Company] & "|" & Text.From([Document_No]),
        type text
    ),

    // 3. Ajout colonne IsInterco (version légère)
    AddIsInterco = Table.AddColumn(
        AddKeyCompanyDoc,
        "IsInterco",
        each false,
        type logical
    )

in
    AddIsInterco;

shared PSI_JAVA_Distribution_2026 = let
    Source = OData.Feed(
        "https://api.businesscentral.dynamics.com/v2.0/ad140881-5aae-4f5d-8941-89111ecfcdcc/Production/ODataV4/Company('JAVA%20Distribution')/PostedSalesInvoicesP143?$filter=Posting_Date ge 2025-01-01",
        null,
        [Implementation="2.0"]
    ),
    AddCompany = Table.AddColumn(Source, "Company", each "JAVA LU", type text),
    AddDocType = Table.AddColumn(AddCompany, "BC_DocumentType", each "Invoice", type text)
in
    AddDocType;

shared PSC_JAVA_Distribution_2025 = let
    Source = OData.Feed(
        "https://api.businesscentral.dynamics.com/v2.0/ad140881-5aae-4f5d-8941-89111ecfcdcc/Production/ODataV4/Company('JAVA%20Distribution')/PostedSalesCreditMemosP144?$filter=Posting_Date ge 2025-01-01",
        null,
        [Implementation="2.0"]
    ),
    AddCompany = Table.AddColumn(Source, "Company", each "JAVA LU", type text),
    AddDocType = Table.AddColumn(AddCompany, "BC_DocumentType", each "Credit Memo", type text)
in
    AddDocType;

shared PSI_JAVA_BE_2025 = let
    Source = OData.Feed(
        "https://api.businesscentral.dynamics.com/v2.0/ad140881-5aae-4f5d-8941-89111ecfcdcc/Production/ODataV4/Company('JAVA%20BE')/PostedSalesInvoicesP143?$filter=Posting_Date ge 2025-01-01",
        null,
        [Implementation="2.0"]
    ),
    AddCompany = Table.AddColumn(Source, "Company", each "JAVA BE", type text),
    AddDocType = Table.AddColumn(AddCompany, "BC_DocumentType", each "Invoice", type text)
in
    AddDocType;

shared PSC_JAVA_BE_2025 = let
    Source = OData.Feed(
        "https://api.businesscentral.dynamics.com/v2.0/ad140881-5aae-4f5d-8941-89111ecfcdcc/Production/ODataV4/Company('JAVA%20BE')/PostedSalesCreditMemosP144?$filter=Posting_Date ge 2025-01-01",
        null,
        [Implementation="2.0"]
    ),
    AddCompany = Table.AddColumn(Source, "Company", each "JAVA BE", type text),
    AddDocType = Table.AddColumn(AddCompany, "BC_DocumentType", each "Credit Memo", type text)
in
    AddDocType;

shared SalesDoc_JAVA_Distribution_2025 = let
    SalesDocs = Table.Combine({PSI_JAVA_Distribution_2026, PSC_JAVA_Distribution_2025})
in
    SalesDocs;

shared SalesDoc_JAVA_BE_2025 = let
    SalesDocs = Table.Combine({PSI_JAVA_BE_2025, PSC_JAVA_BE_2025})
in
    SalesDocs;

shared SalesDoc_2Socs_2025 = let
    // 1. Combine les Sales Docs des deux sociétés
    Combined = Table.Combine({
        SalesDoc_JAVA_Distribution_2025,
        SalesDoc_JAVA_BE_2025
    }),

    // 2. Clé pour la relation avec Value Entries (Company + Document No)
    AddKeyCompanyDoc = Table.AddColumn(
        Combined,
        "Key_Company_Doc",
        each [Company] & "|" & Text.From([No]),
        type text
    ),

    // 3. Clé pour la relation avec IntercoCustomers (Company + Customer No)
    AddKeyCompanyCust = Table.AddColumn(
        AddKeyCompanyDoc,
        "Key_Company_Cust",
        each [Company] & "|" & Text.From([Sell_to_Customer_No]),
        type text
    )

in
    AddKeyCompanyCust;

shared #"Item list" = let
    Source = OData.Feed("https://api.businesscentral.dynamics.com/v2.0/ad140881-5aae-4f5d-8941-89111ecfcdcc/Production/ODataV4/Company('JAVA%20Distribution')/Fiche_article_Excel", null, [Implementation="2.0"])
in
    Source;

shared #"Dimension - DISTRIBUTION" = let
    Source = OData.Feed("https://api.businesscentral.dynamics.com/v2.0/ad140881-5aae-4f5d-8941-89111ecfcdcc/Production/ODataV4/Company('JAVA%20Distribution')/Def_dim?$filter=Table_ID eq 27 and Dimension_Code eq 'ACTIVITÉ' and Dimension_Value_Code eq 'DISTRIBUTION'", null, [Implementation="2.0"])
in
    Source;

shared #"Client list BELU" = let
    // Source JAVA BE
    Source_BE =
        OData.Feed(
            "https://api.businesscentral.dynamics.com/v2.0/ad140881-5aae-4f5d-8941-89111ecfcdcc/Production/ODataV4/Company('JAVA%20BE')/Customer",
            null,
            [Implementation="2.0"]
        ),

    // Source JAVA Distribution
    Source_DIST =
        OData.Feed(
            "https://api.businesscentral.dynamics.com/v2.0/ad140881-5aae-4f5d-8941-89111ecfcdcc/Production/ODataV4/Company('JAVA%20Distribution')/Customer",
            null,
            [Implementation="2.0"]
        ),

    // Combine les deux tables
    Combined =
        Table.Combine({Source_BE, Source_DIST}),

    // Supprime les doublons sur le Customer No (champ clé)
    DistinctCustomers =
        Table.Distinct(Combined, {"Name"})

in
    DistinctCustomers;

shared #"Client list BE" = let
    Source = OData.Feed("https://api.businesscentral.dynamics.com/v2.0/ad140881-5aae-4f5d-8941-89111ecfcdcc/Production/ODataV4/Company('JAVA%20BE')/Customer", null, [Implementation="2.0"])
in
    Source;

shared #"vendor catalog" = let
    Source = OData.Feed("https://api.businesscentral.dynamics.com/v2.0/ad140881-5aae-4f5d-8941-89111ecfcdcc/Production/ODataV4/Company('JAVA%20Distribution')/Item_Vendor_catalog", null, [Implementation="2.0"])
in
    Source;

shared Fournisseurs = let
    Source = OData.Feed("https://api.businesscentral.dynamics.com/v2.0/ad140881-5aae-4f5d-8941-89111ecfcdcc/Production/ODataV4/Company('JAVA%20Distribution')/VendorCard", null, [Implementation="2.0"])
in
    Source;

shared VE_Fige_2025 = let
    Source = Excel.Workbook(
        File.Contents("N:\Administratif et financier\Comptabilité\2026\Reporting mensuel\Java Distribution\VE_ Figé 2025.xlsx"),
        null,
        true
    ),
    Data = Source{[Item="VE_Fige_2025", Kind="Table"]}[Data],

    #"Colonnes conservées" = Table.SelectColumns(
        Data,
        {
            "Item_No",
            "Posting_Date",
            "Document_No",
            "Item_Ledger_Entry_No",
            "Item_Ledger_Entry_Type",
            "Valued_Quantity",
            "Invoiced_Quantity",
            "Cost_Amount_Actual",
            "Sales_Amount_Actual",
            "Company",
            "Key_Company_Doc",
            "IsInterco"
        }
    ),

    #"Types corrigés" = Table.TransformColumnTypes(
        #"Colonnes conservées",
        {
            {"Item_No", type text},
            {"Posting_Date", type date},
            {"Document_No", type text},
            {"Item_Ledger_Entry_No", Int64.Type},
            {"Item_Ledger_Entry_Type", type text},
            {"Valued_Quantity", type number},
            {"Invoiced_Quantity", type number},
            {"Cost_Amount_Actual", type number},
            {"Sales_Amount_Actual", type number},
            {"Company", type text},
            {"Key_Company_Doc", type text},
            {"IsInterco", type logical}
        },
        "fr-FR"
    ),

    #"Nettoyage texte" = Table.TransformColumns(
        #"Types corrigés",
        {
            {"Item_No", each if _ = null then null else Text.Trim(Text.From(_)), type text},
            {"Document_No", each if _ = null then null else Text.Trim(Text.From(_)), type text},
            {"Company", each if _ = null then null else Text.Trim(Text.From(_)), type text},
            {"Key_Company_Doc", each if _ = null then null else Text.Trim(Text.From(_)), type text},
            {"Item_Ledger_Entry_Type", each if _ = null then null else Text.Trim(Text.From(_)), type text}
        }
    )
in
    #"Nettoyage texte";

shared #"Combined_VE_2026-2025" = let
    Source = Table.Combine({VE_2Socs_2026, VE_Fige_2025})
in
    Source;

shared Date = let
    // 1. Définir la période (à adapter si besoin)
    DateDebut = #date(2025, 1, 1),
    DateFin = #date(2030, 12, 31),

    // 2. Générer la liste de dates
    NbJours = Duration.Days(DateFin - DateDebut) + 1,
    ListeDates = List.Dates(DateDebut, NbJours, #duration(1, 0, 0, 0)),

    // 3. Transformer en table
    TableDates = Table.FromList(ListeDates, Splitter.SplitByNothing(), {"Date"}),

    // 4. Typage
    TypeDate = Table.TransformColumnTypes(TableDates, {{"Date", type date}}),

    // 5. Colonnes calendaires
    AddAnnee = Table.AddColumn(TypeDate, "Année", each Date.Year([Date]), Int64.Type),
    AddMois = Table.AddColumn(AddAnnee, "Mois", each Date.Month([Date]), Int64.Type),
    AddNomMois = Table.AddColumn(AddMois, "Nom du mois", each Date.ToText([Date], "MMMM"), type text),
    AddTrimestre = Table.AddColumn(AddNomMois, "Trimestre", each "T" & Number.ToText(Date.QuarterOfYear([Date])), type text),

    // 6. Colonnes utiles pour tri
    AddAnneeMois = Table.AddColumn(AddTrimestre, "AnnéeMois", each [Année] * 100 + [Mois], Int64.Type),

    // 7. Nom court mois (optionnel)
    AddMoisCourt = Table.AddColumn(AddAnneeMois, "Mois court", each Date.ToText([Date], "MMM"), type text)

in
    AddMoisCourt;